name: lint_python
on: [pull_request, push]
jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - run: pip install black codespell flake8 isort mypy pytest pyupgrade safety
      - run: black --check . || true
      - run: codespell --skip="*/FSDL_Final_Model.ipynb"  # --ignore-words-list=""
      - run: flake8 . --count --ignore=E402,F401,F841,W191,W292,W503,W504
               --max-complexity=11 --max-line-length=251 --show-source --statistics
      - run: isort --check-only --profile black . || true
      - run: pip install -r requirements.txt
      - run: mypy --exclude */FSDL_Final_Model.ipynb --ignore-missing-imports . || true
      - run: pytest . || trueW503
      - run: pytest --doctest-modules . || true
      - run: shopt -s globstar && pyupgrade --py36-plus **/*.py || true
      - run: safety check
